version: "3"
services:

  postgres:
    image: postgres:12
    container_name: hack-the-crisis-postgres
    restart: always
    ports:
      - "6002:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hack-the-crisis
    #volumes:
    # - ../pgdata:/var/lib/postgresql/hack-the-crisis/data #keep data outside container

  nestjs-server:
    container_name: hack-the-crisis-nestjs-server
    restart: always
    depends_on:
      - postgres
    ports:
      - "6000:3000"
    build:
      context: ../
      dockerfile: ./docker/BackendLocalDockerfile
    environment:
      PROFILE: docker-local
    command: "yarn start:dev"
    volumes:
      - ../../server/node_modules:/app/node_modules
      - ../../server:/app

  pgadmin:
    container_name: hack-the-crisis-nestjs-pgadmin
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@coderscrew.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "6001:80"
    depends_on:
      - postgres
